/// <---------------------- GENERATOR ---------------------->

function initialize() {
  const now = new Date();
  const formattedDate = now.toLocaleString("en-US");
  let dartCode =
    "// This file is generated by Flart plugin.\n// Please, do not edit this file.\n";
  dartCode += "// ignore_for_file: unnecessary_import, type=lint\n";
  dartCode += `// Last updated: ${formattedDate}\n\n`;
  dartCode += "import 'dart:ui';\n";
  dartCode += "import 'package:flutter/material.dart';\n\n";
  return dartCode;
}
